version: '3.8'

services:
  elementary-codespace:
    build: .
    ports:
      - "6080:6080"
      - "5901:5901"
    environment:
      - VNC_RESOLUTION=1920x1080
      - VNC_PASSWORD=2510
      - DISPLAY=:1
    volumes:
      - ./workspace:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    privileged: true
    shm_size: 2gb
    stdin_open: true
    tty: true