version: '3.8'

services:
  elementary-codespace:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "6080:6080"
      - "5901:5901"
    environment:
      - VNC_RESOLUTION=1920x1080
      - VNC_PASSWORD=codespace
      - DISPLAY=:1
    volumes:
      - ..:/workspace:cached
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    privileged: true
    shm_size: 2gb
    command: /bin/bash -c "while sleep 1000; do :; done"
