#!/bin/bash
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
export XKL_XMODMAP_DISABLE=1
export XDG_CURRENT_DESKTOP="XFCE"
export XDG_SESSION_DESKTOP="xfce"
export XDG_SESSION_TYPE="x11"

# Start dbus
if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
    export $(dbus-launch --sh-syntax)
fi

# Configure X11
xrdb $HOME/.Xresources 2>/dev/null || true
xsetroot -solid grey

# Start desktop environment
exec startxfce4
